apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    helm.sh/chart: webapp-0.1.0
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: webapp
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/managed-by: Helm
  namespace: demo-webapp-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/instance: webapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
        app.kubernetes.io/instance: webapp
    spec:
      imagePullSecrets:
        - name: secret-acr
      serviceAccountName: webapp
      securityContext:
        {}
      containers:
        - name: webapp
          securityContext:
            {}
          image: "crwebdemo.azurecr.io/webapp:1.0.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hello
              port: http
          readinessProbe:
            httpGet:
              path: /hello
              port: http
          resources:
            {}